# Generated by Django 6.0.2 on 2026-02-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'created', 'ordering': ['-publish']},
        ),
    ]
