# Generated by Django 6.0.2 on 2026-02-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='add_tag',
            field=models.CharField(default='', max_length=30),
        ),
    ]
