# Generated by Django 6.0.2 on 2026-02-22 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_add_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='add_tag',
        ),
    ]
