# Generated by Django 6.0.2 on 2026-02-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_customtag_taggedpost_alter_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedpost',
            name='content_object',
        ),
    ]
